---
title: "Travel Behavior"
author: "Nate Lant"
date: "11/19/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(haven)
library(nhts2017)
library(plotly)
library(pander)
library(Hmisc)

source("R/output_functions.R")

knitr::opts_chunk$set(echo = TRUE)
```


## Mode Choice
Below is the distribution of all modes choices and compared by ability. 

```{r mode.choice, echo=F}
# Distribution of trips by mode
# new functions
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid"), age1 = 18, age2 = 65) %>%
  nhts_barplot(trptrans, "Distribution of trips by mode") 


```


## Primary Activity in Previous Week
<!--- PRMACT --->
```{r activity, echo=F, fig.width=10, fig.height=6}
# Distribution of weekly activities
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid")) %>%
  nhts_barplot(prmact, "Distribution of Weekly Activities")

nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid")) %>%
  nhts_distribution(prmact)
             

nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid"), 18, 65) %>%
  nhts2_barplot(prmact, worker, "Distribution of Primary Activity by Worker Status")

nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid"), 18, 65) %>%
  nhts2_barplot(prmact, worker, "Distribution of Primary Activity by Education Level")


```

## Number of trips per day
<!-- cnttdhh count of hh trips on travel day from households. -->
<!-- cnttdtr count of person trips on travel day from persons. -->

```{r trip.number, echo=F}
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid"), 18, 65) %>%
  nhts_boxplot(cnttdtr)

# Scale is way off...

```

<!-- sameplc reason for no trips NOT WORKING-->
```{r trip.reason, echo=F}
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid"), 18, 65) %>%
  nhts_barplot(sameplc)
 # above is not working. lets try it manually
table1 <- nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid"), 18, 65) %>%
    group_by(worker, Ability, sameplc) %>% 
    filter(sameplc > 0,
           worker > 0) %>%
    summarise(Population = sum(wtperfin)) %>%
    as_factor() %>%
    mutate(Distribution = Population/sum(Population))
  
  plot1 <- ggplot(table1, aes(x = sameplc, y = Distribution)) + 
    geom_col(aes(fill = Ability), colour = "Black", position = "dodge") +
    #ggtitle(title, subtitle) +
    #labs(x = xlab, y = ylab) +
    scale_fill_brewer(palette = "PuBuGn", direction = 2) + 
    theme(axis.text.x = element_text(size  = 10, 
                                     angle = 45,
                                     hjust = 1,
                                     vjust = 1)) + 
    facet_wrap(~worker)                        
  #scale_x_discrete(labels = abbreviate)
  
  #return(plot)
  plot1 %>% ggplotly(tooltip = c("x", "y", "fill"))


```

## Trip Purpose
<!--- trip purpose summary: Whytrip1s --->
```{r trip.purpose, echo=F}
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid"), 18, 65) %>%
  nhts2_barplot(whytrp1s, worker, "Trip Purpose by Worker Status")


```

<!--- trip origin purpose: whyfrom --->
<!--- trip destination purpose: whyto --->

## Trip Distance
<!--- TRPMILES --->

```{r trip.miles}
# stat summary of trip distance by work status
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid")) %>%
  nhts_stat_summary(trpmiles)

```

```{r trip.boxplot}
# stat summary of trip distance by work status
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid")) %>%
  nhts2_boxplot(trpmiles, trptrans, worker, title = "Comparison of Trip Distance by Worker Status and mode")

```

## Trip Duration in Minutes
<!--- TRVLCMIN responses 0-1200 --->

```{r min.summary}
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid")) %>%
  nhts_stat_summary(trvlcmin)

```

```{r boxplot.minutes}

# test the function
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid")) %>%
  nhts2_boxplot(trvlcmin, worker, r_sex)

```

## Number of Drivers in Household
<!--- drvrcnt -->

```{r drivers.number}
nhts_clean(nhts_persons, nhts_households, join_by = "houseid") %>%
  nhts_barplot(drvrcnt)

```

## Number of Household Vehicles
<!--- HHVehcnt (might need to blend hh and pers data) --->

## Trip distance in miles for personally driven vehicle trips
<!--- VMT_MILE responses 0-5441 --->

```{r boxplot.personal.miles, echo = F}

# test the function
nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid")) %>%
  nhts2_boxplot(vmt_mile, prmact, worker, "Distribution of Personally Driven Miles by worker group and primary activity")

```





