---
title: "Travel Patterns"
author: "Nate Lant"
date: "12/2/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(haven)
library(nhts2017)
library(plotly)
library(pander)
library(ggpubr)
library(Hmisc)
library(scales)
library(magrittr)
library(reshape2)

source("R/output_functions.R")


knitr::opts_chunk$set(echo = TRUE)
```

## Trip Purpose
According to the 2017 NHTS, trip purpose is different for wheelchair users than for abled users. A histogram below shows the frequency of trips by trip purpose. Only users between the ages of 18 and 65 are considered.

```{r trip.purpose, echo=F}
# This attempt first filters by the ability column
my_persons <- nhts_clean(nhts_trips, nhts_persons, join_by = c("houseid", "personid"), 18, 65) %>%
  group_by(hhpersonid, trippurp) %>% 
  tally()

# data to merge back onto the grid
my_persons_ability <- nhts_persons %>% mutate(hhpersonid = paste(houseid, personid, sep = "-"),
                                              Ability = case_when(w_chair == "07" | w_mtrchr == "08" ~ "Wheelchair",
                                                                  medcond6 == "02" | medcond6 == "03" ~ "Disabled",
                                                                  medcond == "02" ~ "Abled")) %>% 
  filter(r_age >= 18 & r_age < 65,
           Ability != "NA")


# expand grid then join with nhts data. tally the frequency of trip purpose
grid <- expand_grid(hhpersonid = unique(my_persons$hhpersonid), trippurp = unique(my_persons$trippurp))

my_tally <- my_persons %>% right_join(grid) %>%
  mutate(n = ifelse(is.na(n), 0, n)) 

left_join(my_tally, my_persons_ability, "hhpersonid")

```
 Here is how I did it.
```{r trip.purpose.tryagain}
# This attempt contains all trips (all households, persons, etc.)
nhts_persons <- nhts_persons %>% mutate(hhpersonid = paste(houseid, personid, sep = "-"),
                                        Ability = case_when(w_chair == "07" | w_mtrchr == "08" ~ "Wheelchair",
                                                            medcond6 == "02" | medcond6 == "03" ~ "Disabled",  
                                                            medcond == "02" ~ "Abled")) %>% 
    filter(r_age >= 18 & r_age < 65,
           Ability != "NA",
           worker != "NA")

new_trips <- nhts_trips %>% mutate(hhpersonid = paste(houseid, personid, sep = "-")) %>%
  filter(hhpersonid %in% nhts_persons$hhpersonid) %>%
  group_by(hhpersonid, trippurp) %>%
  tally()   # I don't think I need to tally because the histogram will do that for me.

new_grid <- expand_grid(hhpersonid = unique(new_trips$hhpersonid), trippurp = unique(new_trips$trippurp)) %>%
  filter(trippurp != "-9")


# combine the grid and the trips then pipe into a histogram
joined_grid_trips <- new_trips %>% right_join(new_grid) %>%
  mutate(n = ifelse(is.na(n), 0, n)) %>%
  left_join(nhts_persons, "hhpersonid") %>% 
  group_by(Ability)

  # pipe into the histogram
plot <-  ggplot(joined_grid_trips, aes(x = n)) + 
  geom_histogram(aes(y = stat(width*density), fill = Ability), binwidth = 0.8, colour = "black", size = .1, position = "dodge") +
    ggtitle("Comparing the number of trips by trip purpose and worker status", "01 = Employed and 02 = Unemployed") +
    labs(x = "Number of Trips", y = "Percent of subgroup population") +
    scale_fill_brewer(palette = "PuBuGn", direction = 1) + 
    theme(axis.text.x = element_text(size  = 10, 
                                     angle = 45,
                                     hjust = 1,
                                     vjust = 1)) +
    scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
    scale_y_continuous(labels = percent_format()) +
    facet_grid(worker ~ trippurp, scales = "free_x")
  
  plot %>% ggplotly(tooltip = c("x", "y", "fill")) %>% layout(boxmode = "group")

```

Here is how Dr. Macfarlane did it.
```{r macfarlane, echo=F}
# households
my_hh <- nhts_households %>%
  filter(urban == "01") %>% # filtered by urban areas
  filter(msasize == "01") %>% # size less than 250,000
  filter(travday %in% c(sprintf("%02d", 2:6))) %>% # on weekdays
  select(houseid, numadlt, wrkcount, hhsize, hhvehcnt) # kept columns with household details, num of adults, workers, total hh, and vehicles

my_trips <- nhts_trips %>%
  filter(houseid %in% my_hh$houseid) %>%
  group_by(houseid, trippurp) %>% # why not personid?
  tally() 

# household / purpose expander
expander <- expand.grid(
  houseid = unique(my_trips$houseid), trippurp = unique(my_trips$trippurp), 
  stringsAsFactors = FALSE)

my_trips <- my_trips %>% right_join(expander) %>%
  mutate(n = ifelse(is.na(n), 0, n)) %>%
  arrange(houseid)

my_data <- left_join(my_trips, my_hh, by = "houseid") # just stacked on the columns needed.


# here is my addition
nhts_clean(my_trips, nhts_persons, "houseid")

```


## Mode Choice



## Trip Length and Trip Time
